# Generated by Django 4.2.6 on 2023-11-11 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BodegaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id_bodega',
            field=models.ForeignKey(db_column='id_bodega', on_delete=django.db.models.deletion.CASCADE, to='BodegaApp.bodega'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='BodegaApp.tipousuario'),
        ),
    ]
