# Generated by Django 4.2.6 on 2023-10-20 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BodegaApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='rut',
            field=models.ForeignKey(db_column='rut', default=20667345, on_delete=django.db.models.deletion.DO_NOTHING, to='BodegaApp.cliente'),
            preserve_default=False,
        ),
    ]
