# Generated by Django 4.2.6 on 2023-11-11 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BodegaApp', '0003_alter_usuario_id_bodega_alter_usuario_id_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
