# Generated by Django 4.2.6 on 2023-11-13 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BodegaApp', '0004_delete_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='cant_cuotas',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pago',
            name='estado',
            field=models.CharField(default=12, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pago',
            name='id_plan',
            field=models.ForeignKey(blank=True, db_column='id_plan', null=True, on_delete=django.db.models.deletion.SET_NULL, to='BodegaApp.plan'),
        ),
        migrations.AddField(
            model_name='pago',
            name='monto_cuotas',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pago',
            name='orden_compra',
            field=models.CharField(default=12, max_length=26),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pago',
            name='rut',
            field=models.ForeignKey(blank=True, db_column='rut', null=True, on_delete=django.db.models.deletion.SET_NULL, to='BodegaApp.cliente'),
        ),
        migrations.AddField(
            model_name='pago',
            name='tipo_pago',
            field=models.CharField(default=12, max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pago',
            name='descripcion_pago',
            field=models.CharField(max_length=61),
        ),
    ]
