# Generated by Django 4.2.6 on 2023-11-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BodegaApp', '0005_pago_cant_cuotas_pago_estado_pago_id_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='notificaciones',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
