# Generated by Django 4.2.6 on 2023-12-11 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BodegaApp', '0010_alter_cliente_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='despacho',
            name='cant_despachada',
            field=models.IntegerField(default=0),
            preserve_default=False,
        )
    ]
