# Generated by Django 4.2.6 on 2023-12-11 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BodegaApp', '0011_despacho_cant_despachada_alter_colaborador_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='rut',
            field=models.OneToOneField(db_column='rut', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
